"""MarketDataProvider protocol — swap providers by implementing this interface."""
from typing import Protocol, runtime_checkable


@runtime_checkable
class MarketDataProvider(Protocol):
    """
    capabilities: declare what this provider can do.
    Possible values: "documents", "live_price", "recent_financials",
                     "historical_financials", "historical_prices"
    """
    capabilities: frozenset[str]

    def get_scrip_code(self, ticker: str) -> str: ...
    def get_canonical_name(self, scrip_code: str) -> str: ...
    def get_isin(self, scrip_code: str) -> str | None: ...
    def get_financials(self, scrip_code: str) -> list[dict]: ...
    def get_price(self, scrip_code: str) -> dict: ...
    def get_announcements(self, scrip_code: str, days_back: int = 365) -> list[dict]: ...
    def download_pdf(self, attachment_name: str) -> bytes: ...
