"""MarketDataProvider protocol — swap BSE for any other provider by changing one env var."""
from typing import Protocol, runtime_checkable


@runtime_checkable
class MarketDataProvider(Protocol):
    def get_scrip_code(self, ticker: str) -> str: ...
    def get_company_name(self, scrip_code: str) -> str: ...
    def get_financials(self, scrip_code: str) -> dict: ...
    def get_price(self, scrip_code: str) -> dict: ...
    def get_announcements(self, scrip_code: str, days_back: int = 365) -> list[dict]: ...
    def download_pdf(self, attachment_name: str) -> bytes: ...
